package com.incleanhome.mobile.profile.presentation
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.incleanhome.mobile.worker.data.WorkerProfile

@Composable private fun Head(title:String,back:()->Unit){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Button(back){Text("Volver")};Text(title,style=MaterialTheme.typography.headlineSmall)}}
@Composable fun ClientProfileScreen(vm:ClientProfileViewModel,onBack:()->Unit){val s by vm.state.collectAsState();var editing by remember{mutableStateOf(false)};var name by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Head("Mi perfil",onBack);when{ s.loading->CircularProgressIndicator();s.error!=null->{Text(s.error!!,color=MaterialTheme.colorScheme.error);Button(vm::load){Text("Reintentar")}};s.profile!=null->{val p=s.profile!!;if(!editing){Text("Nombre: ${p.name}");Text("Teléfono: ${p.phone?:"-"}");Button({name=p.name;phone=p.phone.orEmpty();editing=true}){Text("Editar perfil")}}else{OutlinedTextField(name,{name=it},label={Text("Nombre")},singleLine=true);OutlinedTextField(phone,{phone=it},label={Text("Teléfono")},singleLine=true);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.save(name,phone) ;editing=false},enabled=!s.saving){Text("Guardar")};TextButton({editing=false}){Text("Cancelar")}}};if(s.saving)CircularProgressIndicator();s.success?.let{Text(it,color=MaterialTheme.colorScheme.primary)}}}}}
@Composable fun WorkerProfileEditScreen(vm:WorkerProfileEditViewModel,onBack:()->Unit){val s by vm.state.collectAsState();val p=s.profile;var name by remember(p){mutableStateOf(p?.name.orEmpty())};var phone by remember(p){mutableStateOf(p?.phone.orEmpty())};var age by remember(p){mutableStateOf(p?.age?.toString().orEmpty())};var exp by remember(p){mutableStateOf(p?.experienceYears?.toString().orEmpty())};var rate by remember(p){mutableStateOf(p?.hourlyRate?.toPlainString().orEmpty())};var services by remember(p){mutableStateOf(p?.serviceTypes?.joinToString(", ").orEmpty())};var zones by remember(p){mutableStateOf(p?.zones?.joinToString(", ").orEmpty())};var bio by remember(p){mutableStateOf(p?.bio.orEmpty())};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Head("Editar perfil",onBack);when{ s.loading->CircularProgressIndicator();s.error!=null&&p==null->{Text(s.error!!,color=MaterialTheme.colorScheme.error);Button(vm::load){Text("Reintentar")}};p!=null->{listOf("Nombre" to name,"Teléfono" to phone,"Edad" to age,"Experiencia (años)" to exp,"Tarifa por hora" to rate,"Servicios (separados por coma)" to services,"Zonas (separadas por coma)" to zones,"Biografía" to bio).forEach{(label,value)->OutlinedTextField(value,{v->when(label){"Nombre"->name=v;"Teléfono"->phone=v;"Edad"->age=v;"Experiencia (años)"->exp=v;"Tarifa por hora"->rate=v;"Servicios (separados por coma)"->services=v;"Zonas (separadas por coma)"->zones=v;else->bio=v}},label={Text(label)},singleLine=label!="Biografía",modifier=Modifier.fillMaxWidth())};Text("Género: ${p.gender}");Button({vm.save(name,phone,age,exp,rate,services,zones,bio)},enabled=!s.saving,modifier=Modifier.fillMaxWidth()){Text("Guardar")};s.saving.let{if(it)CircularProgressIndicator()};s.success?.let{Text(it,color=MaterialTheme.colorScheme.primary)};s.error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}}}}
@Composable fun WorkerStatsScreen(vm:WorkerStatsViewModel,onBack:()->Unit){val s by vm.state.collectAsState();Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Head("Estadísticas",onBack);when{s.loading->CircularProgressIndicator();s.error!=null->{Text(s.error!!,color=MaterialTheme.colorScheme.error);Button(vm::load){Text("Reintentar")}};s.stats!=null->{val x=s.stats!!;Text("Servicios completados: ${x.completedServices}");Text("Calificación promedio: ${x.averageRating}");Text("Servicios por mes",style=MaterialTheme.typography.titleMedium);if(x.monthlyServiceCounts.isEmpty())Text("No hay datos mensuales.") else x.monthlyServiceCounts.forEach{Text("${it.month}: ${it.count}")}}}}}
